Fixes of i18n on readme.md
vtex-apps/product-price pull request #122
Opened 2023-06-28 11:23 UTC by GeorgeLimaDev

#### What problem is this solving?

It relates to task [LOC-10873](https://vtex-dev.atlassian.net/browse/LOC-10873) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).

2023-06-28 20:14 UTC, julia-rabello requested changes

2023-06-28 20:14 UTC, julia-rabello commented on docs/README.md
> +> ℹ️ Currently, **Product Price is the only app that provides product price blocks for your theme**. Both, the [Product Summary Price](https://developers.vtex.com/docs/guides/vtex-product-summary-pro
```suggestion
> ℹ️ Currently, **Product Price is the only app that provides product price blocks for your theme**. The [Product Summary Price](https://developers.vtex.com/docs/guides/vtex-product-summary-productsummaryprice) block from the [Product Summary](https://developers.vtex.com/docs/guides/vtex-product-summary/) app and the [Product Price](https://developers.vtex.com/docs/guides/vtex-store-components-productprice/) block from [Store Components](https://developers.vtex.com/docs/guides/vtex-store-components/) have been deprecated.
```

2023-06-28 20:14 UTC, julia-rabello commented on docs/README.md
> +## Configuring Product Price
```suggestion
## Configuration
```

2023-06-28 20:14 UTC, julia-rabello commented on docs/README.md
> +In the theme `manifest.json`, add the Product Price app as a dependency:
```suggestion
In the theme's `manifest.json` file, add the Product Price app as a dependency:
```

2023-06-28 20:14 UTC, julia-rabello commented on docs/README.md
> +| `paymentSystemName`  | `string`   | This prop allows you to filter the listed installment options by a particular payment system. If not passed, the installments of the payment system with the most
```suggestion
| `paymentSystemName`  | `string`   | Allows you to filter the listed installment options by a particular payment system. If not passed, the installments of the payment system with the most installment options will be rendered.                                                                                                               | `undefined`   |
```

2023-06-28 20:14 UTC, julia-rabello commented on docs/README.md
> +| `installmentsToShow` | `number[]` | Determine the installment options you want to show to the user based on the number of installments. For example, if `[1, 3]` is passed as a value for this prop,
```suggestion
| `installmentsToShow` | `number[]` | Determines the installment options you want to show to the user based on the number of installments. For example, if `[1, 3]` is passed as a value for this prop, only the installments options with `NumberOfInstallments` equal to 1 and 3 will be rendered. If a value is not passed, all options will be rendered. | `undefined`   |
```

2023-06-28 20:14 UTC, julia-rabello commented on docs/README.md
> +| `installmentsCriteria`     | `max-quantity` or `max-quantity-without-interest`               | When set to `max-quantity`, the block will render the installment plan with the most number of install
```suggestion
| `installmentsCriteria`     | `max-quantity` or `max-quantity-without-interest`               | When set to `max-quantity`, the block renders the installment plan with the most number of installments. When set to `max-quantity-without-interest`, the block renders the installment plan with the most number of installments and **no interest**. Note that if this prop is set to `max-quantity-without-interest` and no installment plan matches the 'without interest' criterion, the component will fall back to the default behavior. | `max-quantity` |
```

2023-06-30 14:09 UTC, julia-rabello approved these changes

2023-07-11 18:58 UTC, hellofanny approved these changes

2023-07-11 18:58 UTC, icazevedo approved these changes
Approving so it is mergeable

2023-07-12 10:57 UTC, GeorgeLimaDev commented
![image](https://github.com/vtex-apps/product-price/assets/106821144/f30cb399-db6c-4eeb-b9a6-199f9bd3bd05)
@vtex-apps/store-framework-devs please merge it as well since I am not authorized to do so. Thanks.

2023-07-13 19:08 UTC, merged