Fix app types
vtex-apps/product-price pull request #54
Opened 2020-12-21 17:03 UTC by klzns

#### What problem is this solving?

When importing the components from other apps the types were not working.

#### How to test it?

https://pricets--storecomponents.myvtex.com/
https://brenovtex--carrefourbrfood.myvtex.com/busca/panetone
https://brenovtex--motorolauk.myvtex.com/
https://brenovtex--dzarm.myvtex.com/novidades
https://pricets--sandboxusdev.myvtex.com/

#### Screenshots or example usage:

No layout change is expected.

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](put .gif link here - can be found under "advanced" on giphy)

2020-12-21 17:23 UTC, klzns commented on react/components/InstallmentsContext.ts
> -export interface Installments {
This type as written as plural (installments) but it refer to a singular installment.

2020-12-21 17:54 UTC, icazevedo approved these changes
LGTM, although the Installments List is showing everything in the same line.

<img width="1100" alt="Screen Shot 2020-12-21 at 2 54 26 PM" src="https://user-images.githubusercontent.com/8127610/102806887-6dbd1700-439c-11eb-9d75-5572909856ca.png">

2020-12-21 18:03 UTC, kaisermann approved these changes

2020-12-21 18:10 UTC, klzns commented on react/ListPrice.tsx
> +})
I can't, I use the variable `messages` in default props

2020-12-21 18:20 UTC, kaisermann approved these changes

2020-12-21 18:51 UTC, victorhmp requested changes

2020-12-21 18:51 UTC, victorhmp commented on react/Installments.tsx
> +  let [maxInstallment] = commercialOffer.Installments
I think changing this from `maxInstallments` to `maxInstallment` could be misleading. The max _installments_, would be the payment options with the highest number of individual installments. While the max _installment_ would be the highest individual installment value, which in this case is the opposite of what you want, right?

2020-12-21 18:51 UTC, victorhmp commented on react/InstallmentsList.tsx
> +          <InstallmentsItem installment={inst} key={i}>
Also think changing this from `installments` to `installment` is not a good idea

2020-12-21 18:51 UTC, victorhmp commented on react/InstallmentsList.tsx
> +  installment: ProductTypes.Installment
Same thing

2020-12-22 13:17 UTC, Klynger approved these changes

2020-12-22 13:17 UTC, Klynger commented on react/InstallmentsList.tsx
> +      {pickedInstallments.map((inst, i: number) => {
```suggestion
      {pickedInstallments.map((inst, i) => {
```

2020-12-22 17:01 UTC, victorhmp approved these changes

2020-12-22 17:03 UTC, merged