Added taxValue prop
vtex-apps/product-price pull request #56
Opened 2021-01-06 14:07 UTC by razvanudream

#### What problem is this solving?

Adding taxValue prop to show the value of the tax for when a client requests that instead of the percentage or alongside the percentage.

#### How to test it?

[Workspace](https://razvan--vetrob2c.myvtex.com/felibio-pch-r1-doza-2932/p) - need to be logged in to see the tax

#### Screenshots or example usage:

I replaced the taxPercentage message prop with taxValue to show the change in this case:

Before:
![image](https://user-images.githubusercontent.com/71461884/103777027-fb556380-5038-11eb-9b95-51b6f629a3a0.png)

After:
![image](https://user-images.githubusercontent.com/71461884/103775998-7f0e5080-5037-11eb-8046-dd766d8a0c0a.png)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/62PP2yEIAZF6g/giphy.gif)

2021-02-03 13:34 UTC, victorhmp requested changes
The code looks good to me, awesome work @razvanudream!
And thanks for updating the docs 😄 ! Could also update the CHANGELOG? You just need to describe what you've changed (or added in this case) right below the `## [Unreleased]` header

2021-02-03 13:46 UTC, razvanudream commented
> The code looks good to me, awesome work @razvanudream!
> And thanks for updating the docs  ! Could also update the CHANGELOG? You just need to describe what you've changed (or added in this case) right below the `## [Unreleased]` header

Hi - awesome, cheers!  I updated forked master with upstream master and then rebased master into my own branch to avoid any conflicts for you during the release.  Pushed changes for CHANGELOG as well.

2021-02-03 13:49 UTC, victorhmp approved these changes

2021-02-03 18:07 UTC, igorbrasileiro approved these changes
LGTM

2021-02-04 14:11 UTC, merged

2021-02-04 14:22 UTC, victorhmp commented
@allcontributors add @razvanudream for code