Added new message variable
vtex-apps/product-price pull request #72
Opened 2021-04-22 20:34 UTC by Git-the-Sanz

#### What problem is this solving?

Originally, if you had singular installments there was no way to differentiate messages using the existing variables; because the IOMessages received values that couldn't be parsed with ICU.

With these modifications, you now have a Message Variable that can be used in the ICU Messages, to differentiate plural from singular messages. 

#### How to test it?

Go to Admin -> Site editor -> Select 'product-installment' app in any 'Product-summary' -> And see the Installments message

[Develop](https://develop--eistoreqa.myvtex.com/)

An example of an ICU message:
```
{
   hasMoreThanOne, select,
   false { En 1 pago sin interés }
   true {Hasta {installmentsNumber} cuotas { hasInterest, select, true{de {installmentValue}} false{sin interés} 
   other{ } } }
   other { }
 }
```

hasMoreThanOne is now a boolean that can be use as a select to have different messages in singular and plural

#### Screenshots or example usage:

Before if you had only 1, there was no way to singularize a message:
<img width="1193" alt="before" src="https://user-images.githubusercontent.com/50715158/115780681-5aa16e80-a3b1-11eb-8434-4d1b019eea92.png">

After:
<img width="1193" alt="after" src="https://user-images.githubusercontent.com/50715158/115780674-583f1480-a3b1-11eb-8cd8-d6d616f8e90d.png">

IOMessages variables are rendered as <span /> so you cannot use PLURAL in ICU:
<img width="859" alt="iomessages" src="https://user-images.githubusercontent.com/50715158/115780687-5b3a0500-a3b1-11eb-996d-235cfadc88cc.png">

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/3o85xDWOG8Sbl9yQzm/giphy.gif)

2021-04-26 18:28 UTC, Git-the-Sanz commented
@klzns @firstdoit @gustavorosolem @lbebber Hello, I know this is not a critical fix. But nonetheless it's affecting all stores in Latin locales as this is a common implementation.

2021-04-26 18:30 UTC, Git-the-Sanz commented
@icazevedo Hello Ícaro, I know this is not a critical fix. But it's affecting all latin stores, as this is a common implementation.

2021-04-26 18:32 UTC, klzns requested changes
Thanks for the pull request! It looks good. It's only missing the changelog entry. Do you mind adding it? I think the bot left a comment the PR giving instructions.

2021-04-26 20:32 UTC, klzns approved these changes

2021-04-27 12:43 UTC, merged

2021-04-27 12:55 UTC, klzns commented
@allcontributors add @Git-the-Sanz for code